name: wind-integral
channels:
  - astropy
  - conda-forge
dependencies:
  - python>=3.7
  - requests
  - matplotlib
  - astropy
  - astroquery
  - jupyter
  - jupyterlab
  - nodejs # Needed to install jupyterlab extensions
  - numpy
  - pandas
  - plotly
  - plotly-orca # Needed to export plotly plots
  - psutil
  - pip:
    - cdflib